#!/bin/bash
set -euo pipefail

# ------------------------------------------------------------------
# setup.sh - Environment file generator for TPC India Courier
#
# Reads env-manifest.json and creates independent .env files
# in each target package/app directory.
#
# Usage:
#   ./setup.sh          Dev mode (uses defaults, auto-generates secrets)
#   ./setup.sh --prod   Production mode (prompts for required values)
#   ./setup.sh --force  Force-recreate all .env files (backs up existing)
# ------------------------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MANIFEST="$SCRIPT_DIR/env-manifest.json"
MODE="dev"

# Parse arguments
for arg in "$@"; do
  case "$arg" in
    --prod)  MODE="prod" ;;
    --force) MODE="force" ;;
    --help|-h)
      echo "Usage: ./setup.sh [--prod|--force]"
      echo "  (default)  Dev mode - uses defaults, auto-generates secrets"
      echo "  --prod     Prompts for required variables interactively"
      echo "  --force    Backs up and recreates all .env files from scratch"
      exit 0
      ;;
  esac
done

# ------------------------------------------------------------------
# Preflight checks
# ------------------------------------------------------------------

if ! command -v jq &>/dev/null; then
  echo "Error: jq is required but not installed."
  echo "  Install: sudo apt install jq  (or brew install jq)"
  exit 1
fi

if [ ! -f "$MANIFEST" ]; then
  echo "Error: env-manifest.json not found at $MANIFEST"
  exit 1
fi

# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------

resolve_value() {
  local key="$1"
  local default_val="$2"
  local generate_cmd="$3"
  local required="$4"

  # In prod mode, prompt for required vars with empty defaults
  if [ "$MODE" = "prod" ] && [ "$required" = "true" ] && [ -z "$default_val" ]; then
    read -rp "  Enter value for $key: " user_val
    if [ -n "$user_val" ]; then
      echo "$user_val"
      return
    fi
  fi

  # If there's a generate command and default is empty, generate it
  if [ -n "$generate_cmd" ] && [ -z "$default_val" ]; then
    local generated
    generated=$(eval "$generate_cmd" 2>/dev/null) || true
    if [ -n "$generated" ]; then
      echo "$generated"
      return
    fi
  fi

  echo "$default_val"
}

# Append a variable to a file only if it doesn't already exist
append_if_missing() {
  local file="$1"
  local key="$2"
  local value="$3"
  local comment="$4"

  if grep -qE "^${key}=" "$file" 2>/dev/null; then
    return 1  # Already exists
  fi

  # Add comment if provided
  if [ -n "$comment" ]; then
    echo "# $comment" >> "$file"
  fi
  echo "${key}=${value}" >> "$file"
  return 0
}

# ------------------------------------------------------------------
# Collect all unique target files
# ------------------------------------------------------------------

mapfile -t TARGET_FILES < <(
  jq -r '.variables[].targets[]' "$MANIFEST" | sort -u
)

echo ""
echo "TPC India Courier - Environment Setup"
echo "======================================"
echo "Mode: $MODE"
echo "Targets: ${TARGET_FILES[*]}"
echo ""

# ------------------------------------------------------------------
# Process each target file
# ------------------------------------------------------------------

CREATED=0
UPDATED=0
SKIPPED=0

# Safe increment to avoid set -e tripping on ((0++))
inc() { eval "$1=\$(( $1 + 1 ))"; }

for target in "${TARGET_FILES[@]}"; do
  target_path="$SCRIPT_DIR/$target"
  target_dir="$(dirname "$target_path")"

  # Ensure directory exists
  mkdir -p "$target_dir"

  # Remove old symlinks - we want real files
  if [ -L "$target_path" ]; then
    echo "  Removing symlink: $target"
    rm "$target_path"
  fi

  # Force mode: back up and recreate
  if [ "$MODE" = "force" ] && [ -f "$target_path" ]; then
    cp "$target_path" "${target_path}.bak"
    echo "  Backed up: $target -> ${target}.bak"
    rm "$target_path"
  fi

  is_new=false
  if [ ! -f "$target_path" ]; then
    is_new=true
    # Create file with header
    {
      echo "# Auto-generated by setup.sh - $(date +%Y-%m-%d)"
      echo "# Do not commit this file. Edit env-manifest.json to add variables."
      echo ""
    } > "$target_path"
  fi

  # Get all variables that target this file
  var_count=$(jq -r --arg t "$target" \
    '[.variables[] | select(.targets[] == $t)] | length' "$MANIFEST")

  added=0
  for i in $(seq 0 $((var_count - 1))); do
    key=$(jq -r --arg t "$target" --argjson i "$i" \
      '[.variables[] | select(.targets[] == $t)][$i].key' "$MANIFEST")
    default_val=$(jq -r --arg t "$target" --argjson i "$i" \
      '[.variables[] | select(.targets[] == $t)][$i].default // ""' "$MANIFEST")
    comment=$(jq -r --arg t "$target" --argjson i "$i" \
      '[.variables[] | select(.targets[] == $t)][$i].comment // ""' "$MANIFEST")
    generate_cmd=$(jq -r --arg t "$target" --argjson i "$i" \
      '[.variables[] | select(.targets[] == $t)][$i].generate // ""' "$MANIFEST")
    required=$(jq -r --arg t "$target" --argjson i "$i" \
      '[.variables[] | select(.targets[] == $t)][$i].required // false' "$MANIFEST")

    value=$(resolve_value "$key" "$default_val" "$generate_cmd" "$required")

    if append_if_missing "$target_path" "$key" "$value" "$comment"; then
      inc added
    fi
  done

  if [ "$is_new" = true ]; then
    echo "  Created: $target ($added variables)"
    inc CREATED
  elif [ "$added" -gt 0 ]; then
    echo "  Updated: $target (+$added new variables)"
    inc UPDATED
  else
    echo "  Up to date: $target"
    inc SKIPPED
  fi
done

# ------------------------------------------------------------------
# Generate .env.example files (keys only, no values)
# ------------------------------------------------------------------

echo ""
echo "Generating .env.example files..."

for target in "${TARGET_FILES[@]}"; do
  target_path="$SCRIPT_DIR/$target"
  example_path="${target_path}.example"

  if [ -f "$target_path" ]; then
    # Extract keys from the .env file, skip comments and blank lines
    {
      echo "# Example env file - copy to .env and fill in values"
      echo ""
      grep -E "^[A-Z_]+=" "$target_path" | sed 's/=.*/=/' || true
    } > "$example_path"
  fi
done

echo "  Done."

# ------------------------------------------------------------------
# Also create a root .env for dotenv-cli (used by turbo)
# ------------------------------------------------------------------

ROOT_ENV="$SCRIPT_DIR/.env"
if [ ! -f "$ROOT_ENV" ] || [ "$MODE" = "force" ]; then
  if [ "$MODE" = "force" ] && [ -f "$ROOT_ENV" ]; then
    cp "$ROOT_ENV" "${ROOT_ENV}.bak"
  fi

  echo ""
  echo "Creating root .env (for dotenv-cli/turbo)..."

  {
    echo "# Root env - used by dotenv-cli for turbo commands"
    echo "# Auto-generated by setup.sh - $(date +%Y-%m-%d)"
    echo ""
  } > "$ROOT_ENV"

  # Collect all unique variables across all targets
  mapfile -t ALL_KEYS < <(jq -r '.variables[].key' "$MANIFEST" | sort -u)

  for key in "${ALL_KEYS[@]}"; do
    default_val=$(jq -r --arg k "$key" \
      '.variables[] | select(.key == $k) | .default // ""' "$MANIFEST" | head -1)
    comment=$(jq -r --arg k "$key" \
      '.variables[] | select(.key == $k) | .comment // ""' "$MANIFEST" | head -1)
    generate_cmd=$(jq -r --arg k "$key" \
      '.variables[] | select(.key == $k) | .generate // ""' "$MANIFEST" | head -1)
    required=$(jq -r --arg k "$key" \
      '.variables[] | select(.key == $k) | .required // false' "$MANIFEST" | head -1)

    value=$(resolve_value "$key" "$default_val" "$generate_cmd" "$required")

    append_if_missing "$ROOT_ENV" "$key" "$value" "$comment" || true
  done

  echo "  Created root .env"
fi

# ------------------------------------------------------------------
# Summary
# ------------------------------------------------------------------

echo ""
echo "Setup complete!"
echo "  Created: $CREATED | Updated: $UPDATED | Up to date: $SKIPPED"
echo ""
echo "Next steps:"
echo "  1. Review .env files and fill in missing values (Google OAuth, etc.)"
echo "  2. Run: pnpm install"
echo "  3. Run: pnpm db:migrate"
echo "  4. Run: pnpm db:seed:all"
echo "  5. Run: pnpm dev"
echo ""
