import UserService from "@repo/services/user";
import ProductTypeService from "@repo/services/product-type";
import ServiceTypeService from "@repo/services/service-type";
import ModeTypeService from "@repo/services/mode-type";
import BranchService from "@repo/services/branch";
import DestinationService from "@repo/services/destination";
import CustomerService from "@repo/services/customer";
import PricingRuleService from "@repo/services/pricing-rule";
import ShipmentService from "@repo/services/shipment";
import InvoiceService from "@repo/services/invoice";
import NotificationConfigService from "@repo/services/notification";
import DashboardService from "@repo/services/dashboard";
import CustomerAuthService from "@repo/services/customer-auth";
import CustomerPortalService from "@repo/services/customer-portal";

export const userService = new UserService();
export const productTypeService = new ProductTypeService();
export const serviceTypeService = new ServiceTypeService();
export const modeTypeService = new ModeTypeService();
export const branchService = new BranchService();
export const destinationService = new DestinationService();
export const customerService = new CustomerService();
export const pricingRuleService = new PricingRuleService();
export const shipmentService = new ShipmentService();
export const invoiceService = new InvoiceService();
export const notificationConfigService = new NotificationConfigService();
export const dashboardService = new DashboardService();
export const customerAuthService = new CustomerAuthService();
export const customerPortalService = new CustomerPortalService();
